import { useCallback, useEffect, useRef, useState } from 'react';
import Head from 'next/head';
import Crossword from 'react-crossword-near';
import { createGridData, loadGuesses } from 'react-crossword-near/dist/es/util';
import sha256 from 'js-sha256';

import { parseSolutionSeedPhrase, viewMethodOnContract } from '_utils';
import data from '_utils/hardcoded_data';
import getConfig from '_config';

const Home = () => {
    const crossword = useRef();
    const [solutionFound, setSolutionFound] = useState('Not correct yet');

    // const [data, setData] = useState(null);
    const [solutionHash, setSolutionHash] = useState(null);

    useEffect(async () => {
        const nearConfig = getConfig(process.env.NEXT_PUBLIC_NEAR_ENV);
        const solutionHash = viewMethodOnContract(nearConfig, 'get_solution');

        setSolutionHash(solutionHash);
    }, []);

    const onCrosswordComplete = useCallback(async completeCount => {
        if (completeCount) {
            let gridData = createGridData(data).gridData;
            loadGuesses(gridData, 'guesses');
            await checkSolution(gridData);
        }
    }, []);

    const checkSolution = gridData => {
        let seedPhrase = parseSolutionSeedPhrase(data, gridData);
        let answerHash = sha256.sha256(seedPhrase);

        if (answerHash === solutionHash) {
            setSolutionFound('Correct!');
        } else {
            setSolutionFound('Not correct yet');
        }
    };

    return (
        <>
            <Head>
                <title>VTS crossword puzzle</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.png" />
            </Head>
            <h1>NEAR Crossword Puzzle</h1>
            <main id="crossword-wrapper">
                <h3>Status: {solutionFound}</h3>
                <Crossword data={data} ref={crossword} onCrosswordComplete={onCrosswordComplete} />
            </main>
            <p className="thanks">
                Thank you{' '}
                <a href="https://github.com/JaredReisinger/react-crossword" target="_blank" rel="noreferrer">
                    @jaredreisinger/react-crossword
                </a>
                !
            </p>
        </>
    );
};

export default Home;
